version: '3.9'

services:
    pokepersistence:
        image: postgres
        container_name: pgdb
        environment:
            POSTGRES_DB: "pokeDB"
            POSTGRES_PASSWORD: "_password_"
        networks:
            filenet:
                aliases:
                    - postgres
        ports:
            - 5432:5432
        volumes:
            - pgconf:/etc/postgresql
            - pglogs:/var/log/postgresql
            - pgdata:/var/lib/postgresql/data
        deploy:
            restart_policy:
                condition: on-failure

networks:
    filenet:

volumes:
    pgconf:
    pglogs:
    pgdata:
